# Generated by Django 4.0.4 on 2022-05-02 04:31

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=40)),
                ('Facility', models.CharField(choices=[('MultiUseFacility', 'MultiUseFacility'), ('ComplexFacility', 'ComplexFacility'), ('ElderlyFacility', 'ElderlyFacility'), ('UndergroundFacility', 'UndergroundFacility')], default='MultiUseFacility', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('description', models.CharField(max_length=100)),
                ('scheduledDate', models.DateField()),
            ],
        ),
    ]
