# Generated by Django 4.0.4 on 2022-05-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
