# Generated by Django 4.0.4 on 2022-05-02 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_delete_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactionarea',
            old_name='created',
            new_name='Created',
        ),
        migrations.RemoveField(
            model_name='interactionarea',
            name='id',
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
