# Generated by Django 4.0.4 on 2022-05-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0003_rename_created_interactionarea_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionarea',
            name='ID',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
