# Generated by Django 4.0.4 on 2022-05-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_alter_interactionarea_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactionarea',
            name='ID',
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='id',
            field=models.BigAutoField(auto_created=True, default=9, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
