# Generated by Django 4.0.4 on 2022-05-02 04:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_remove_interactionarea_id_interactionarea_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactionarea',
            name='id',
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
