# Generated by Django 4.0.4 on 2022-05-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenario', '0008_delete_interactionarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=40)),
                ('Facility', models.CharField(choices=[('MultiUseFacility', 'MultiUseFacility'), ('ComplexFacility', 'ComplexFacility'), ('ElderlyFacility', 'ElderlyFacility'), ('UndergroundFacility', 'UndergroundFacility')], default='MultiUseFacility', max_length=25)),
            ],
        ),
    ]
