# Generated by Django 4.0.4 on 2022-05-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transform3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionX', models.FloatField()),
                ('PositionY', models.FloatField()),
                ('PositionZ', models.FloatField()),
                ('RotationX', models.FloatField()),
                ('RotationY', models.FloatField()),
                ('RotationZ', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='Collider_Size_X',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='Collider_Size_Y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='Collider_Size_Z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='Type',
            field=models.CharField(choices=[('move_floor', 'move_floor'), ('floor', 'floor'), ('area', 'area')], default='area', max_length=20),
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='Next1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Next1', to='scenario.transform3d'),
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='Next2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Next2', to='scenario.transform3d'),
        ),
        migrations.AddField(
            model_name='interactionarea',
            name='Transform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Transform', to='scenario.transform3d'),
        ),
    ]
