# Generated by Django 4.0.4 on 2022-05-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0011_combinedscenario_cutscene_evaluation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasform',
            new_name='Transform',
        ),
    ]
