# Generated by Django 4.0.4 on 2022-05-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firexr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedscenario',
            name='Scenarios',
        ),
        migrations.AddField(
            model_name='combinedscenario',
            name='Scenarios',
            field=models.ManyToManyField(to='firexr.separatedscenario'),
        ),
    ]
