# Generated by Django 4.0.4 on 2022-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firexr', '0002_remove_combinedscenario_scenarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedscenario',
            name='Scenarios',
            field=models.ManyToManyField(blank=True, to='firexr.separatedscenario'),
        ),
    ]
