# Generated by Django 4.0.4 on 2022-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firexr', '0003_alter_combinedscenario_scenarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fds',
            name='FDSFileID',
        ),
        migrations.AddField(
            model_name='fds',
            name='FDSFileID',
            field=models.ManyToManyField(blank=True, to='firexr.fdsfile'),
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='ActivateObjects',
        ),
        migrations.AddField(
            model_name='objectinfo',
            name='ActivateObjects',
            field=models.ManyToManyField(blank=True, related_name='activate_objects', to='firexr.objectinfo'),
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='DeactivateObjects',
        ),
        migrations.AddField(
            model_name='objectinfo',
            name='DeactivateObjects',
            field=models.ManyToManyField(blank=True, related_name='deactivate_objects', to='firexr.objectinfo'),
        ),
        migrations.RemoveField(
            model_name='separatedscenario',
            name='Evaluations',
        ),
        migrations.AddField(
            model_name='separatedscenario',
            name='Evaluations',
            field=models.ManyToManyField(blank=True, to='firexr.evaluation'),
        ),
        migrations.RemoveField(
            model_name='separatedscenario',
            name='XREvents',
        ),
        migrations.AddField(
            model_name='separatedscenario',
            name='XREvents',
            field=models.ManyToManyField(blank=True, to='firexr.xrevent'),
        ),
    ]
