# Generated by Django 4.0.4 on 2022-05-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firexr', '0005_rename_fdsfileid_fds_fdsfiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactionpoint',
            name='LocalTransform',
        ),
        migrations.AddField(
            model_name='interactionpoint',
            name='LocalTransform',
            field=models.ManyToManyField(blank=True, null=True, related_name='transformposes', to='firexr.transform'),
        ),
    ]
