# Generated by Django 4.0.4 on 2022-05-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firexr', '0007_rename_name_evaluation_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionpoint',
            name='Facility',
            field=models.IntegerField(choices=[('Global', 0), ('MultiUseFacility', 1), ('ComplexFacility', 2), ('ElderlyFacility', 3), ('UndergroundFacility', 4)], default=0),
        ),
    ]
