# Generated by Django 4.0.4 on 2022-05-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firexr', '0008_alter_interactionpoint_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedscenario',
            name='Facility',
            field=models.IntegerField(choices=[('Global', 0), ('MultiUseFacility', 1), ('ComplexFacility', 2), ('ElderlyFacility', 3), ('UndergroundFacility', 4)], default=0),
        ),
        migrations.AddField(
            model_name='separatedscenario',
            name='Facility',
            field=models.IntegerField(choices=[('Global', 0), ('MultiUseFacility', 1), ('ComplexFacility', 2), ('ElderlyFacility', 3), ('UndergroundFacility', 4)], default=0),
        ),
    ]
