# Generated by Django 4.0.4 on 2022-05-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firexr', '0009_combinedscenario_facility_separatedscenario_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedscenario',
            name='TargetFacility',
        ),
        migrations.RemoveField(
            model_name='separatedscenario',
            name='TargetFacility',
        ),
    ]
